# This file was *autogenerated* from the file pathwidth.sage
from sage.all_cmdline import *   # import sage library
_sage_const_999 = Integer(999); _sage_const_5 = Integer(5)#from sage.graphs.graph_decompositions.vertex_separation import path_decomposition
from graph import Graph as MyGraph
from bitset import BitSet
from plot import plot

x = BitSet(_sage_const_999 )
l = len(x)
print(l)
print(x.tolist(l))

graph = MyGraph.generate_random(_sage_const_5 , _sage_const_5 )
plot(graph)
#M = Matrix(graph.adjacency_matrix())
#print(M)
#G = Graph(M)
#print(G)
